TECHNICAL_SKILLS = [
    "python",
    "java",
    "javascript",
    "html",
    "css",
    "sql",
    "flask",
    "django",
    "react",
    "nodejs",
    "docker",
    "aws",
    "git",
    "github",
    "tableau",
    "power bi",
    "machine learning",
    "deep learning",
    "nlp",
    "selenium",
    "cypress",
    "spring boot",
    "mongodb",
    "mysql",
    "postgresql",
    "pandas",
    "numpy",
    "scikit-learn",
    "tensorflow",
    "data analysis",
    "data visualization",
    "kubernetes",
    "angular"
    "ai",
    "natural language processing",
    "cloud computing",
    "kotlin",
    "rest api",
    "pytorch",
    "excel",
    "statistics",
    "bootstrap",
    "algorithms",
    "object oriented programming",
    "linux",
    "microservices",
    "data structure"
]

SOFT_SKILLS = [
    "communication",
    "teamwork",
    "leadership",
    "problem solving",
    "critical thinking",
    "adaptability",
    "time management",
    "collaboration",
    "presentation skill"
]